name: scalable_flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # For Dependency Injection
  injectable: ^1.2.0
  get_it: ^6.0.0

  # For Model
  freezed_annotation: ^0.14.0
  json_annotation: ^4.0.0

  # For Architecture
  pmvvm: ^2.0.1

  # For Networking
  dio: ^4.0.0-beta5

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:

  # For Model
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2

  # For Dependency Injection
  injectable_generator: ^1.2.0

  # For Code Generation
  build_runner:
  source_gen: ^0.9.10+3

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    #------------------------------------------------------------------
